default: &default
  adapter: mysql2
  charset: utf8mb4
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  pool: 5
  username: root
  password: root
  host: localhost

development:
  <<: *default
  database: church_development

test:
  <<: *default
  database: church_test
  
production:
  <<: *default
  database: <%= ENV['CHURCH_DATABASE_DATABASE'] %>
  username: <%= ENV['CHURCH_DATABASE_USERNAME'] %>
  password: <%= ENV['CHURCH_DATABASE_PASSWORD'] %>